package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Cd'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Cd")) {
    expectSteps {
        powerShell {
            name = "Power Shell Deploy"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            scriptMode = script {
                content = """
                    Remove-Item -path D:\test\* -recurse;
                    Copy-Item ".\hari\*" "D:\test\";
                    Copy-Item ".\hari\bin\*" "D:\test\bin\";
                    Copy-Item ".\hari\bin\roslyn\*" "D:\test\bin\roslyn\";
                    Copy-item ".\hari\Content\*" "D:\test\Content\";
                    Copy-Item ".\hari\fonts\*" "D:\test\fonts\";
                    Copy-Item ".\hari\Scripts\*" "D:\test\Scripts\"
                    Copy-Item ".\hari\Scripts\WebForms\*" "D:\test\Scripts\WebForms\";
                    Copy-Item ".\hari\Scripts\WebForms\MSAjax\*" "D:\test\Scripts\WebForms\MSAjax\";
                    
                    Import-Module WebAdministration;
                    cd IIS:\AppPools\;
                    
                      ${'$'}appPool = ${'$'}null;
                      ${'$'}name = "Hello8";
                    
                    
                      if (!(Test-Path ${'$'}name -pathType container))
                      {
                        ${'$'}appPool = New-Item ${'$'}name;    
                      }
                      else
                      {
                        ${'$'}appPool = Get-Item ${'$'}name;    
                      }
                      
                        
                      ${'$'}appPool.Enable32BitAppOnWin64 = ${'$'}enable32BitAppOnWin64;
                    
                    
                    
                    
                        New-Website -Name ${'$'}name -Port 8089 -IPAddress "*" -HostHeader ${'$'}url -PhysicalPath "D:\test\" -ApplicationPool ${'$'}name;
                """.trimIndent()
            }
        }
    }
    steps {
        update<PowerShellStep>(0) {
            scriptMode = file {
                path = "script/psScript.ps1"
            }
        }
    }
}
